on:
  push:
    branches:
      - "main"
name: deploy to Amazon-ECS

env: 
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: kasim-test
  ECS_CLUSTER: test-kasim

jobs: 
  job1: 
    name: Deploy 
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout
      uses: actions/checkout@v3
    - name: Deploy
      id: build-image
      run: |
        ehco "deploying" 

  job2:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: general
        SLACK_COLOR: ${{ job1.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: ${{ job1.status }}
        SLACK_TITLE: Post Title
        SLACK_USERNAME: rtCamp
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}    
